# Generated by Django 3.1.6 on 2021-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_sizes',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, null=True),
        ),
    ]
